# Generated by Django 4.2.6 on 2023-11-24 14:27

from django.db import migrations, models
import django.db.models.deletion
import memotracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=15)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('document_date', models.DateField(blank=True, null=True)),
                ('encryption_key', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='home/projectx/Documents')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.documentcategory')),
                ('content_type', memotracker.models.ContentTypeModelField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Owner Type')),
            ],
        ),
    ]
