# Generated by Django 4.2.6 on 2023-11-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='D:\\MemoTracking\\projectx\\Documents'),
        ),
    ]
