# Generated by Django 4.2.6 on 2023-12-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='home/projectx/Documents'),
        ),
    ]
