# Generated by Django 4.2.6 on 2024-11-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_alter_document_privacy_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shared_with',
        ),
    ]
