# Generated by Django 4.2.6 on 2024-11-07 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0012_remove_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(related_name='documents_shared_with', through='dms.SharedDocument', to=settings.AUTH_USER_MODEL),
        ),
    ]
