# Generated by Django 4.2.6 on 2024-11-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_document_shared_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_create_document', 'Can create document'), ('can_share_document', 'Can share document'), ('can_update_document', 'Can update document'), ('can_delete_document', 'Can delete document')]},
        ),
    ]
