# Generated by Django 4.2.6 on 2024-11-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
