# Generated by Django 4.2.6 on 2024-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0016_alter_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
