# Generated by Django 4.2.6 on 2024-11-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
