# Generated by Django 4.2.6 on 2024-12-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(unique=True, upload_to='Documents'),
        ),
    ]
