# Generated by Django 4.2.6 on 2024-12-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0019_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Documents'),
        ),
    ]
