# Generated by Django 4.2.6 on 2025-01-06 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organogram', '0022_businessunit_bu_signature'),
        ('dms', '0020_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='business_unit_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organogram.businessunit'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organogram.externalcustomer'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
