# Generated by Django 4.2.6 on 2025-01-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0021_document_business_unit_owner_document_external_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='business_unit_owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='external_owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
    ]
