# Generated by Django 4.2.6 on 2025-01-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0029_alter_memoroute_status'),
        ('dms', '0022_remove_document_business_unit_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='linked_memos',
            field=models.ManyToManyField(blank=True, related_name='linked_documents', to='memotracker.memo'),
        ),
    ]
