# Generated by Django 4.2.6 on 2025-01-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0023_document_linked_memos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='linked_memos',
        ),
    ]
