# Generated by Django 4.2.6 on 2025-01-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0025_memotodms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memotodms',
            name='remarks',
        ),
    ]
