# Generated by Django 4.2.6 on 2025-01-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0023_businessunit_external_footer_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0026_remove_memotodms_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='object_id',
        ),
        migrations.AddField(
            model_name='document',
            name='owner_business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_owned_by_business_unit', to='organogram.businessunit'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_external_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_owned_by_external_customer', to='organogram.externalcustomer'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_owned_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
