# Generated by Django 4.2.6 on 2025-01-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0028_remove_document_owner_business_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
