# Generated by Django 4.2.6 on 2025-01-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0029_alter_document_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='keywords',
        ),
    ]
