# Generated by Django 4.2.6 on 2025-01-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0030_remove_document_author_remove_document_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
    ]
