# Generated by Django 4.2.6 on 2023-11-24 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('memotracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'user'), ('model', 'businessunit'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Owner Type'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
