# Generated by Django 4.2.6 on 2023-11-24 13:26

from django.db import migrations
import django.db.models.deletion
import memotracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('memotracker', '0002_alter_memo_assigned_to_alter_memo_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content_type',
            field=memotracker.models.ContentTypeModelField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Owner Type'),
        ),
    ]
