# Generated by Django 4.2.6 on 2023-12-01 08:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0004_memoattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
