# Generated by Django 4.2.6 on 2023-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0005_alter_memo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
