# Generated by Django 4.2.6 on 2023-12-01 12:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0006_alter_memo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
