# Generated by Django 4.2.6 on 2023-12-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0008_alter_memo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('closed', 'Closed')], default='draft'),
        ),
        migrations.AlterField(
            model_name='memoattachment',
            name='memo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='memotracker.memo'),
        ),
    ]
