# Generated by Django 4.2.6 on 2024-01-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0010_alter_memo_keywords_alter_memo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Medium'), ('low', 'Low')], default='Low'),
        ),
    ]
