# Generated by Django 4.2.6 on 2024-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0010_alter_memo_keywords_alter_memo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoroute',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
