# Generated by Django 4.2.6 on 2024-01-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0012_alter_memo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
