# Generated by Django 4.2.6 on 2024-01-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('memotracker', '0013_memo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Owner Type'),
        ),
    ]
