# Generated by Django 4.2.6 on 2024-01-23 07:48

from django.db import migrations
import django.db.models.deletion
import organogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('memotracker', '0014_alter_memo_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content_type',
            field=organogram.models.ContentTypeModelField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Owner Type'),
        ),
    ]
