# Generated by Django 4.2.6 on 2024-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0012_alter_memoroute_status'),
        ('memotracker', '0015_alter_memo_content_type'),
    ]

    operations = [
    ]
