# Generated by Django 4.2.6 on 2024-01-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0016_merge_20240127_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='priority',
        ),
        migrations.AddField(
            model_name='memo',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
