# Generated by Django 4.2.6 on 2024-02-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0017_remove_memo_priority_memo_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoattachment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
