# Generated by Django 4.2.6 on 2024-02-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0017_alter_memo_reference_number'),
        ('memotracker', '0017_remove_memo_priority_memo_urgent'),
    ]

    operations = [
    ]
