# Generated by Django 4.2.6 on 2024-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0018_memoattachment_remark'),
        ('memotracker', '0018_merge_20240202_0824'),
    ]

    operations = [
    ]
