# Generated by Django 4.2.6 on 2024-02-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0019_merge_20240208_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='attached_memos',
            field=models.ManyToManyField(blank=True, related_name='memo_attachments', to='memotracker.memo'),
        ),
    ]
