# Generated by Django 4.2.6 on 2024-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0019_merge_20240208_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoroute',
            name='carbon_copy',
            field=models.BooleanField(default=False),
        ),
    ]
