# Generated by Django 4.2.6 on 2024-02-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0020_memoroute_carbon_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('description_am', models.CharField()),
            ],
        ),
    ]
