# Generated by Django 4.2.6 on 2024-02-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0021_memoaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoroute',
            name='memo_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memotracker.memoaction'),
        ),
    ]
