# Generated by Django 4.2.6 on 2024-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0021_alter_memo_attached_memos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='attached_memos',
            field=models.ManyToManyField(blank=True, to='memotracker.memo'),
        ),
    ]
