# Generated by Django 4.2.6 on 2024-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0022_memoroute_memo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoroute',
            name='status',
            field=models.CharField(choices=[('notseen', 'Not Seen'), ('seen', 'Seen'), ('forwarded', 'Forwarded'), ('closed', 'Closed')], default='notseen'),
        ),
    ]
