# Generated by Django 4.2.6 on 2024-02-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0022_alter_memo_attached_memos'),
        ('memotracker', '0022_memoroute_memo_action'),
    ]

    operations = [
    ]
