# Generated by Django 4.2.6 on 2024-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0023_merge_20240220_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='privacy',
        ),
        migrations.AddField(
            model_name='memo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
