# Generated by Django 4.2.6 on 2024-02-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0023_alter_memoroute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoroute',
            name='is_for_bu',
            field=models.BooleanField(default=False),
        ),
    ]
