# Generated by Django 4.2.6 on 2024-03-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('memotracker', '0024_memoroute_is_for_bu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoroute',
            name='is_for_bu',
        ),
        migrations.AddField(
            model_name='memoroute',
            name='destination_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memoroute',
            name='destination_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Destination Type'),
        ),
    ]
