# Generated by Django 4.2.6 on 2024-02-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0023_merge_20240220_1713'),
        ('memotracker', '0024_remove_memo_privacy_memo_public'),
    ]

    operations = [
    ]
