# Generated by Django 4.2.6 on 2024-03-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0025_merge_20240222_1546'),
        ('memotracker', '0025_remove_memoroute_is_for_bu_memoroute_destination_id_and_more'),
    ]

    operations = [
    ]
