# Generated by Django 4.2.6 on 2024-03-16 09:57

from django.db import migrations
import django.db.models.deletion
import organogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('memotracker', '0026_merge_20240312_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoroute',
            name='destination_type',
            field=organogram.models.ContentTypeModelField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Destination Type'),
        ),
    ]
