# Generated by Django 4.2.6 on 2024-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0028_memo_in_english_memo_to_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoroute',
            name='status',
            field=models.CharField(choices=[('notseen', 'Not Seen'), ('seen', 'Seen'), ('reversed', 'Reversed'), ('forwarded', 'Forwarded'), ('closed', 'Closed')], default='notseen'),
        ),
    ]
