# Generated by Django 4.2.6 on 2025-01-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memotracker', '0030_memodetailtodms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoDetailToDMS',
        ),
    ]
