# Generated by Django 4.2.6 on 2024-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread'),
        ),
    ]
