# Generated by Django 4.2.6 on 2024-03-24 07:55
# Generated by Django 4.2.6 on 2024-04-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'ordering': ['-notification__created_date']},
        ),
    ]
