# Generated by Django 4.2.6 on 2023-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name_am',
            field=models.CharField(max_length=200, verbose_name='Name(am)'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name_en',
            field=models.CharField(max_length=200, verbose_name='Name(en)'),
        ),
        migrations.AlterField(
            model_name='externalcustomer',
            name='name_am',
            field=models.CharField(max_length=200, verbose_name='Name(am)'),
        ),
        migrations.AlterField(
            model_name='externalcustomer',
            name='name_en',
            field=models.CharField(max_length=200, verbose_name='Name(en)'),
        ),
    ]
