# Generated by Django 4.2.6 on 2023-12-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0005_permissionparent_alter_permission_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['order']},
        ),
    ]
