# Generated by Django 4.2.6 on 2023-12-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0006_alter_permission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['permission__order']},
        ),
    ]
