# Generated by Django 4.2.6 on 2024-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0008_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcustomer',
            options={'ordering': ['name_en']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='Documents'),
        ),
    ]
