# Generated by Django 4.2.6 on 2024-01-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0010_alter_businessunit_options'),
        ('organogram', '0010_businessunit_last_memo_ref_number'),
    ]

    operations = [
    ]
