# Generated by Django 4.2.6 on 2024-01-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0011_merge_20240130_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=None),
        ),
    ]
