# Generated by Django 4.2.6 on 2024-02-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0012_role_is_manager_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='Documents'),
        ),
    ]
