# Generated by Django 4.2.6 on 2024-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0016_profile_security_answer_1_profile_security_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_personal_memo_ref_number',
            field=models.IntegerField(default=0),
        ),
    ]
