# Generated by Django 4.2.6 on 2024-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0017_profile_last_personal_memo_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcustomer',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
