# Generated by Django 4.2.6 on 2024-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0019_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
