# Generated by Django 4.2.6 on 2024-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0020_profile_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
