# Generated by Django 4.2.6 on 2024-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0021_role_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='bu_signature',
            field=models.ImageField(blank=True, null=True, upload_to='digital_signature/'),
        ),
    ]
