# Generated by Django 4.2.6 on 2025-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0022_businessunit_bu_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='external_footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='footers/external/'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='external_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='headers/external/'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='internal_footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='footers/internal/'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='internal_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='headers/internal/'),
        ),
    ]
