# Generated by Django 4.2.6 on 2025-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0023_businessunit_external_footer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_question_1',
            field=models.CharField(choices=[('Your birth year', 'Your birth year'), ("Your grandmother's name", "Your grandmother's name"), ('Name of your elementary school', 'Name of your elementary school'), ('Your favorite color', 'Your favorite color'), ("Your first pet's name", "Your first pet's name"), ('City where you were born', 'City where you were born')], default='Your birth year', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='security_question_2',
            field=models.CharField(blank=True, choices=[('Your birth year', 'Your birth year'), ("Your grandmother's name", "Your grandmother's name"), ('Name of your elementary school', 'Name of your elementary school'), ('Your favorite color', 'Your favorite color'), ("Your first pet's name", "Your first pet's name"), ('City where you were born', 'City where you were born')], default="Your grandmother's name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='security_question_3',
            field=models.CharField(blank=True, choices=[('Your birth year', 'Your birth year'), ("Your grandmother's name", "Your grandmother's name"), ('Name of your elementary school', 'Name of your elementary school'), ('Your favorite color', 'Your favorite color'), ("Your first pet's name", "Your first pet's name"), ('City where you were born', 'City where you were born')], default='Name of your elementary school', max_length=100, null=True),
        ),
    ]
