# Generated by Django 4.2.6 on 2025-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0024_alter_profile_security_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
