# Generated by Django 4.2.6 on 2025-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0026_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_am',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
