# Generated by Django 4.2.6 on 2025-03-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0027_profile_name_am'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_am',
        ),
    ]
