# Generated by Django 4.2.6 on 2025-03-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0028_remove_profile_name_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name_am',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
